name: Build and Deploy DocC

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Swift 6
        run: |
          wget https://download.swift.org/swift-6.2-release/ubuntu2404/swift-6.2-RELEASE/swift-6.2-RELEASE-ubuntu24.04.tar.gz
          tar xzf swift-6.2-RELEASE-ubuntu24.04.tar.gz
          echo "$PWD/swift-6.2-RELEASE-ubuntu24.04/usr/bin" >> $GITHUB_PATH
      
      - name: Generate DocC
        run: |
          swift build
          swift package generate-documentation \
            --output-path ./docs-archives
          
          # Use plugin to convert
          swift package plugin \
            --package-path . \
            convert-documentation \
            --output-path ./docs \
            --hosting-base-path KeyringAccess \
            ./docs-archives/KeyringAccess.doccarchive
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
